schema_version = "1.0.0"

id = "timeoffset"
name = "TimeOffset"
version = "1.5.0"
tagline = "Biblioteca de desenhos no blender"
maintainer = "Rapadura Atômica LTDA"
type = "add-on"
tags = ["workflow", "2D Animation", "Rigging"]
license = ["SPDX:GPL-3.0-or-later"]
blender_version_min = "4.2.0"
website = "https://rapaduraatomica.com.br/"
copyright = ["2025-2026 Rapadura Atômica LTDA"]